from __future__ import annotations

COMMON_CHARGE_COMPONENTS: tuple[dict[str, str | bool], ...] = (
    {"component_code": "BASE_FREIGHT", "component_name": "Base Freight", "category": "FREIGHT", "default_party_role": "BOTH", "charge_context": "TRANSPORT", "calculation_basis": "SHIPMENT"},
    {"component_code": "AIR_FREIGHT", "component_name": "Air Freight", "category": "FREIGHT", "default_party_role": "BOTH", "charge_context": "TRANSPORT", "calculation_basis": "WEIGHT"},
    {"component_code": "LINE_HAUL", "component_name": "Line Haul", "category": "FREIGHT", "default_party_role": "BOTH", "charge_context": "TRANSPORT", "calculation_basis": "DISTANCE"},
    {"component_code": "DRAYAGE", "component_name": "Drayage", "category": "FREIGHT", "default_party_role": "BOTH", "charge_context": "TRANSPORT", "calculation_basis": "CONTAINER"},
    {"component_code": "PICKUP", "component_name": "Pickup", "category": "ORIGIN", "default_party_role": "BOTH", "charge_context": "ORIGIN", "calculation_basis": "SHIPMENT"},
    {"component_code": "ORIGIN_HANDLING", "component_name": "Origin Handling", "category": "HANDLING", "default_party_role": "BOTH", "charge_context": "ORIGIN", "calculation_basis": "CONTAINER"},
    {"component_code": "DESTINATION_HANDLING", "component_name": "Destination Handling", "category": "HANDLING", "default_party_role": "BOTH", "charge_context": "DESTINATION", "calculation_basis": "CONTAINER"},
    {"component_code": "EXPORT_CUSTOMS_CLEARANCE", "component_name": "Export Customs Clearance", "category": "CUSTOMS", "default_party_role": "BOTH", "charge_context": "ORIGIN", "calculation_basis": "SHIPMENT"},
    {"component_code": "IMPORT_CUSTOMS_CLEARANCE", "component_name": "Import Customs Clearance", "category": "CUSTOMS", "default_party_role": "BOTH", "charge_context": "DESTINATION", "calculation_basis": "SHIPMENT"},
    {"component_code": "CUSTOMS_EXAM", "component_name": "Customs Exam", "category": "CUSTOMS", "default_party_role": "BOTH", "charge_context": "CUSTOMS", "calculation_basis": "SHIPMENT"},
    {"component_code": "DUTY", "component_name": "Duty", "category": "TAX", "default_party_role": "PAYER", "charge_context": "CUSTOMS", "calculation_basis": "PERCENTAGE", "is_tax": True},
    {"component_code": "VAT_GST_TAX", "component_name": "VAT/GST Tax", "category": "TAX", "default_party_role": "PAYER", "charge_context": "TAX", "calculation_basis": "PERCENTAGE", "is_tax": True},
    {"component_code": "INSURANCE", "component_name": "Insurance", "category": "INSURANCE", "default_party_role": "BOTH", "charge_context": "COMMERCIAL", "calculation_basis": "PERCENTAGE"},
    {"component_code": "FUEL_SURCHARGE", "component_name": "Fuel Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "TRANSPORT", "calculation_basis": "PERCENTAGE"},
    {"component_code": "CURRENCY_ADJUSTMENT", "component_name": "Currency Adjustment", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "COMMERCIAL", "calculation_basis": "PERCENTAGE"},
    {"component_code": "SECURITY_SURCHARGE", "component_name": "Security Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "COMPLIANCE", "calculation_basis": "SHIPMENT"},
    {"component_code": "PEAK_SEASON_SURCHARGE", "component_name": "Peak Season Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "TRANSPORT", "calculation_basis": "CONTAINER"},
    {"component_code": "PORT_CONGESTION", "component_name": "Port Congestion", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "PORT", "calculation_basis": "CONTAINER"},
    {"component_code": "TOLL", "component_name": "Toll", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "TRANSPORT", "calculation_basis": "SHIPMENT"},
    {"component_code": "LIFT_ON_LIFT_OFF", "component_name": "Lift On Lift Off", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "PORT", "calculation_basis": "CONTAINER"},
    {"component_code": "REEFER_SURCHARGE", "component_name": "Reefer Surcharge", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "EQUIPMENT", "calculation_basis": "CONTAINER"},
    {"component_code": "HAZMAT_SURCHARGE", "component_name": "Hazmat Surcharge", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "COMMODITY", "calculation_basis": "SHIPMENT"},
    {"component_code": "STORAGE", "component_name": "Storage", "category": "TIME_BASED", "default_party_role": "BOTH", "charge_context": "WAREHOUSE", "calculation_basis": "DAY"},
    {"component_code": "DEMURRAGE", "component_name": "Demurrage", "category": "TIME_BASED", "default_party_role": "BOTH", "charge_context": "PORT", "calculation_basis": "DAY"},
    {"component_code": "DETENTION", "component_name": "Detention", "category": "TIME_BASED", "default_party_role": "BOTH", "charge_context": "EQUIPMENT", "calculation_basis": "DAY"},
    {"component_code": "ORIGIN_DOCUMENTATION", "component_name": "Origin Documentation", "category": "DOCUMENTATION", "default_party_role": "BOTH", "charge_context": "ORIGIN", "calculation_basis": "DOCUMENT"},
    {"component_code": "AWB_DOCUMENTATION", "component_name": "AWB Documentation", "category": "DOCUMENTATION", "default_party_role": "BOTH", "charge_context": "AIR", "calculation_basis": "DOCUMENT"},
    {"component_code": "WEIGHBRIDGE_VGM", "component_name": "Weighbridge/VGM", "category": "DOCUMENTATION", "default_party_role": "BOTH", "charge_context": "COMPLIANCE", "calculation_basis": "CONTAINER"},
    {"component_code": "SCREENING", "component_name": "Screening", "category": "COMPLIANCE", "default_party_role": "BOTH", "charge_context": "SECURITY", "calculation_basis": "SHIPMENT"},
    {"component_code": "ROUNDING_ADJUSTMENT", "component_name": "Rounding Adjustment", "category": "ADJUSTMENT", "default_party_role": "BOTH", "charge_context": "FINANCE", "calculation_basis": "FLAT"},
    {"component_code": "MANUAL_ADJUSTMENT", "component_name": "Manual Adjustment", "category": "ADJUSTMENT", "default_party_role": "BOTH", "charge_context": "FINANCE", "calculation_basis": "FLAT"},
    {"component_code": "MARGIN_MARKUP", "component_name": "Margin Markup", "category": "MARGIN", "default_party_role": "PAYEE", "charge_context": "COMMERCIAL", "calculation_basis": "FLAT"},
    {"component_code": "ROAD_FREIGHT_FTL", "component_name": "Road Freight - Full Truckload", "category": "FREIGHT", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "ROAD_FREIGHT_LTL", "component_name": "Road Freight - Less Than Truckload", "category": "FREIGHT", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "WEIGHT", "default_calculation_profile_code": "WEIGHT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "ROAD_FUEL_SURCHARGE", "component_name": "Road Fuel Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "PERCENTAGE", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "ROAD_TOLL", "component_name": "Road Toll", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "DISTANCE", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "ROAD_CONGESTION_SURCHARGE", "component_name": "Road Congestion Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "LOW_EMISSION_ZONE_SURCHARGE", "component_name": "Low Emission Zone Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "WAITING_TIME", "component_name": "Waiting Time", "category": "TIME_BASED", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "PER_HOUR", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "LOADING_SERVICE", "component_name": "Loading Service", "category": "HANDLING", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "UNLOADING_SERVICE", "component_name": "Unloading Service", "category": "HANDLING", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "TAIL_LIFT_SERVICE", "component_name": "Tail Lift Service", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "ADR_DANGEROUS_GOODS", "component_name": "ADR Dangerous Goods Surcharge", "category": "COMPLIANCE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "TEMPERATURE_CONTROL", "component_name": "Temperature Controlled Transport", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "PALLET_EXCHANGE", "component_name": "Pallet Exchange", "category": "EQUIPMENT", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "PER_PALLET", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "MULTI_STOP_SURCHARGE", "component_name": "Multi-stop Surcharge", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "PER_STOP", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "REDELIVERY", "component_name": "Redelivery", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "FAILED_COLLECTION", "component_name": "Failed Collection", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "DELIVERY_APPOINTMENT", "component_name": "Delivery Appointment", "category": "ACCESSORIAL", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "REMOTE_AREA_SURCHARGE", "component_name": "Remote Area Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "OVERWEIGHT_SURCHARGE", "component_name": "Overweight Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "WEIGHT", "default_calculation_profile_code": "WEIGHT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "OVERSIZE_SURCHARGE", "component_name": "Oversize Surcharge", "category": "SURCHARGE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_VOLUME_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "SPECIAL_TRANSPORT_PERMIT", "component_name": "Special Transport Permit", "category": "COMPLIANCE", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "FLAT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
    {"component_code": "CMR_DOCUMENTATION", "component_name": "CMR Documentation", "category": "DOCUMENTATION", "default_party_role": "BOTH", "charge_context": "ROAD", "calculation_basis": "DOCUMENT", "default_calculation_profile_code": "FLAT_AMOUNT", "allocation_profile_code": "ROAD_WEIGHT_TO_ITEM", "business_date_profile_code": "ROAD_SHIPMENT_STANDARD"},
)


COMMON_CHARGE_ALLOCATION_PROFILES: tuple[dict[str, object], ...] = (
    {
        "profile_code": "DIRECT_HEADER_DEFAULT",
        "profile_name": "Direct Header Allocation",
        "version_number": 1,
        "source_level": "HOUSE",
        "source_to_house_driver": None,
        "house_to_item_driver": None,
        "final_posting_level": "HOUSE",
        "default_quantity_uom": None,
        "notes": "Single-step allocation profile for direct document or header-level posting.",
        "settings_json": {"shape": "DIRECT"},
    },
    {
        "profile_code": "STAGED_CONTAINER_ITEM_DEFAULT",
        "profile_name": "Staged Container Allocation",
        "version_number": 1,
        "source_level": "CONTAINER",
        "source_to_house_driver": "CBM",
        "house_to_item_driver": "WEIGHT",
        "final_posting_level": "PO_SCHEDULE_LINE",
        "default_quantity_uom": "CBM",
        "notes": "Two-stage allocation profile for intermediate container-to-target propagation.",
        "settings_json": {"shape": "STAGED"},
    },
    {
        "profile_code": "MANUAL_TARGET_DEFAULT",
        "profile_name": "Manual Target Allocation",
        "version_number": 1,
        "source_level": "SHIPMENT",
        "source_to_house_driver": "CBM",
        "house_to_item_driver": "WEIGHT",
        "final_posting_level": "PO_SCHEDULE_LINE",
        "default_quantity_uom": None,
        "notes": "Manual allocation profile with no automatic basis defaults.",
        "settings_json": {"shape": "MANUAL"},
    },
    {
        "profile_code": "ROAD_WEIGHT_TO_ITEM",
        "profile_name": "Road charge by weight",
        "version_number": 1,
        "source_level": "SHIPMENT",
        "source_to_house_driver": "WEIGHT",
        "house_to_item_driver": "WEIGHT",
        "final_posting_level": "PO_SCHEDULE_LINE",
        "default_quantity_uom": "KG",
        "notes": "Allocates road shipment charges to Houses and items by gross weight.",
        "settings_json": {"shape": "ROAD", "driver": "WEIGHT"},
    },
    {
        "profile_code": "ROAD_VOLUME_TO_ITEM",
        "profile_name": "Road charge by volume",
        "version_number": 1,
        "source_level": "SHIPMENT",
        "source_to_house_driver": "CBM",
        "house_to_item_driver": "CBM",
        "final_posting_level": "PO_SCHEDULE_LINE",
        "default_quantity_uom": "CBM",
        "notes": "Allocates road shipment charges to Houses and items by cubic volume.",
        "settings_json": {"shape": "ROAD", "driver": "CBM"},
    },
    {
        "profile_code": "ROAD_EQUAL_TO_ITEM",
        "profile_name": "Road charge equally by item",
        "version_number": 1,
        "source_level": "SHIPMENT",
        "source_to_house_driver": "COUNT",
        "house_to_item_driver": "COUNT",
        "final_posting_level": "PO_SCHEDULE_LINE",
        "default_quantity_uom": "EA",
        "notes": "Allocates road shipment charges equally when physical measures are unavailable.",
        "settings_json": {"shape": "ROAD", "driver": "COUNT"},
    },
)


COMMON_CHARGE_CALCULATION_PROFILES: tuple[dict[str, object], ...] = (
    {
        "profile_code": "FLAT_AMOUNT",
        "profile_name": "Flat amount",
        "description": "Uses the provided amount directly without factor multiplication.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "FLAT_AMOUNT",
        "rate_uom": None,
        "missing_factor_policy": "BLOCK",
        "factors": (),
    },
    {
        "profile_code": "QUANTITY",
        "profile_name": "Rate per quantity",
        "description": "Multiplies the unit rate by the target quantity.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "UNIT",
        "missing_factor_policy": "BLOCK",
        "factors": (
            (1, "QUANTITY", "Quantity", "QUANTITY", "UNIT"),
        ),
    },
    {
        "profile_code": "WEIGHT",
        "profile_name": "Rate per weight",
        "description": "Multiplies the unit rate by gross weight.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "KG",
        "missing_factor_policy": "BLOCK",
        "factors": (
            (1, "WEIGHT", "Weight", "WEIGHT", "KG"),
        ),
    },
    {
        "profile_code": "VOLUME",
        "profile_name": "Rate per volume",
        "description": "Multiplies the unit rate by gross volume.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "CBM",
        "missing_factor_policy": "BLOCK",
        "factors": (
            (1, "VOLUME", "Volume", "VOLUME", "CBM"),
        ),
    },
    {
        "profile_code": "PER_CONTAINER",
        "profile_name": "Rate per container",
        "description": "Multiplies the unit rate by eligible container count.",
        "version_number": 1,
        "application_level": "CONTAINER",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "CONTAINER",
        "missing_factor_policy": "BLOCK",
        "factors": (
            (1, "CONTAINER_COUNT", "Container count", "CONTAINER_COUNT", "CONTAINER"),
        ),
    },
    {
        "profile_code": "PER_HOUSE",
        "profile_name": "Rate per house",
        "description": "Multiplies the unit rate by approved house count.",
        "version_number": 1,
        "application_level": "HOUSE",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "HOUSE",
        "missing_factor_policy": "BLOCK",
        "factors": (
            (1, "HOUSE_COUNT", "House count", "HOUSE_COUNT", "HOUSE"),
        ),
    },
    {
        "profile_code": "PER_DAY",
        "profile_name": "Rate per day",
        "description": "Multiplies the unit rate by duration in days.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "DAY",
        "missing_factor_policy": "BLOCK",
        "factors": (
            (1, "DURATION_DAYS", "Duration days", "DURATION_DAYS", "DAY"),
        ),
    },
    {
        "profile_code": "PER_CONTAINER_PER_HOUR",
        "profile_name": "Rate per container per hour",
        "description": "Multiplies the unit rate by container count and duration hours.",
        "version_number": 1,
        "application_level": "CONTAINER",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "CONTAINER_HOUR",
        "missing_factor_policy": "BLOCK",
        "factors": (
            (1, "CONTAINER_COUNT", "Container count", "CONTAINER_COUNT", "CONTAINER"),
            (2, "DURATION_HOURS", "Duration hours", "DURATION_HOURS", "HOUR"),
        ),
    },
    {
        "profile_code": "PER_KILOMETER",
        "profile_name": "Rate per kilometer",
        "description": "Multiplies the unit rate by caller-supplied route distance in kilometers.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "KM",
        "missing_factor_policy": "BLOCK",
        "factors": ((1, "DISTANCE_KM", "Distance", "MANUAL", "KM"),),
    },
    {
        "profile_code": "PER_STOP",
        "profile_name": "Rate per stop",
        "description": "Multiplies the unit rate by caller-supplied pickup and delivery stop count.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "STOP",
        "missing_factor_policy": "BLOCK",
        "factors": ((1, "STOP_COUNT", "Stops", "MANUAL", "STOP"),),
    },
    {
        "profile_code": "PER_PALLET",
        "profile_name": "Rate per pallet",
        "description": "Multiplies the unit rate by caller-supplied pallet count.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "PALLET",
        "missing_factor_policy": "BLOCK",
        "factors": ((1, "PALLET_COUNT", "Pallets", "MANUAL", "PALLET"),),
    },
    {
        "profile_code": "PER_LOADING_METER",
        "profile_name": "Rate per loading meter",
        "description": "Multiplies the unit rate by caller-supplied loading meters.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "LDM",
        "missing_factor_policy": "BLOCK",
        "factors": ((1, "LOADING_METERS", "Loading meters", "MANUAL", "LDM"),),
    },
    {
        "profile_code": "PER_HOUR",
        "profile_name": "Rate per hour",
        "description": "Multiplies the unit rate by duration in hours.",
        "version_number": 1,
        "application_level": "SHIPMENT",
        "calculation_method": "RATE_TIMES_PRODUCT",
        "rate_uom": "HOUR",
        "missing_factor_policy": "BLOCK",
        "factors": ((1, "DURATION_HOURS", "Duration hours", "DURATION_HOURS", "HOUR"),),
    },
)


COMMON_BUSINESS_DATE_PROFILES: tuple[dict[str, object], ...] = (
    {
        "profile_code": "OCEAN_HOUSE_STANDARD",
        "profile_name": "Ocean House Exchange Rate Policy",
        "description": "Fallback chain for ocean-house exchange-rate date resolution.",
        "version_number": 1,
        "steps": (
            {
                "step_number": 10,
                "date_key": "SHIPPED_ON_BOARD_DATE",
                "notes": "Prefer shipped-on-board date when the source system provides it.",
            },
            {
                "step_number": 20,
                "date_key": "SHIPMENT_ACTUAL_DEPARTURE_DATE",
                "notes": "Fallback to the actual departure date.",
            },
            {
                "step_number": 30,
                "date_key": "SHIPMENT_PLANNED_DEPARTURE_DATE",
                "notes": "Fallback to the estimated departure date.",
            },
        ),
    },
    {
        "profile_code": "AIR_HOUSE_STANDARD",
        "profile_name": "Air House Exchange Rate Policy",
        "description": "Fallback chain for air-house exchange-rate date resolution.",
        "version_number": 1,
        "steps": (
            {
                "step_number": 10,
                "date_key": "ACTUAL_FLIGHT_DEPARTURE_DATE",
                "notes": "Prefer the actual flight departure date when available.",
            },
            {
                "step_number": 20,
                "date_key": "AWB_EXECUTION_DATE",
                "notes": "Fallback to the air waybill execution date.",
            },
            {
                "step_number": 30,
                "date_key": "ESTIMATED_FLIGHT_DEPARTURE_DATE",
                "notes": "Fallback to the estimated flight departure date.",
            },
        ),
    },
    {
        "profile_code": "ROAD_SHIPMENT_STANDARD",
        "profile_name": "Road Shipment Exchange Rate Policy",
        "description": "Fallback chain for road-shipment exchange-rate date resolution.",
        "version_number": 1,
        "steps": (
            {
                "step_number": 10,
                "date_key": "ROAD_ACTUAL_PICKUP_DATE",
                "notes": "Use the actual road pickup date supplied by the caller.",
            },
            {
                "step_number": 20,
                "date_key": "ROAD_PLANNED_PICKUP_DATE",
                "notes": "Fallback to the planned road pickup date.",
            },
            {
                "step_number": 30,
                "date_key": "CMR_ISSUE_DATE",
                "notes": "Fallback to the CMR or e-CMR consignment-note issue date.",
            },
            {
                "step_number": 40,
                "date_key": "DOCUMENT_DATE",
                "notes": "Fallback to the charge document date.",
            },
        ),
    },
)
